version: '3'
services:
  crunch:
    build:
      context: .
      dockerfile: Dockerfile
      tags:
        - crunch:latest
    hostname: crunch
    image: crunch:latest
    volumes:
      - crunch-data:/data
    ports:
      - "80:5000"
    restart: always
volumes:
  crunch-data: