apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd-image-updater.argoproj.io/image-list: myapp=kregistry.ddns.net/promo2026/crunch
    argocd-image-updater.argoproj.io/myapp.update-strategy: digest
    argocd-image-updater.argoproj.io/write-back-method: git
  generation: 20
  name: crunch
  namespace: argocd
spec:
  destination:
    namespace: crunch
    server: https://kubernetes.default.svc
  project: default
  source:
    directory:
      jsonnet: {}
      recurse: true
    path: k8s
    repoURL: https://github.com/sysakdemy/crunch.git
    targetRevision: HEAD