apiVersion: v1
kind: Service
metadata:
  labels:
    app: crunch
  name: crunch-service
  namespace: crunch
spec:
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 30294
    port: 80
    protocol: TCP
    targetPort: 5000
  selector:
    app: crunch
  sessionAffinity: None
  type: LoadBalancer