apiVersion: v1
kind: Service
metadata:
  annotations:
    cloud.google.com/neg: '{"ingress":true}'
  creationTimestamp: "2025-06-19T20:50:29Z"
  finalizers:
  - gke.networking.io/l4-netlb-v1
  - service.kubernetes.io/load-balancer-cleanup
  labels:
    app: crunch
  name: crunch-service
  namespace: crunch
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 34.118.226.60
  clusterIPs:
  - 34.118.226.60
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 30294
    port: 80
    protocol: TCP
    targetPort: 5000
  selector:
    app: crunch
    app.kubernetes.io/managed-by: cloud-console
  sessionAffinity: None
  type: LoadBalancer