apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
    traefik.ingress.kubernetes.io/router.middlewares: default-redirect-https@kubernetescrd
  generation: 1
  name: crunch-ingress
  namespace: crunch
spec:
  ingressClassName: traefik
  tls:
  - hosts:
    - monapp.ddns.net
    secretName: crunch-tls
  rules:
  - host: monapp.ddns.net
    http:
      paths:
      - backend:
          service:
            name: crunch-svc
            port:
              number: 80
        path: /
        pathType: Prefix