apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yml
  - hpa.yml
  - ingress.yml
  - namespace.yml
  - redirect-https.yml
  - service.yml

images:
  - name: kregistry.ddns.net/promo2026/crunch
    newTag: latest